name: Setup JBang

description: 'Set up a specific version of JBang and add it to the PATH'

branding:
  icon: 'archive'
  color: 'gray-dark'

inputs:
  version:
    description: 'The version of JBang to download'
    default: 'latest'
    required: true

  setup-java:
    default: 'true'
    description: 'Setup internal Java runtime.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Download JBang'
      shell: bash
      if: runner.os != 'Windows'
      run: |
        echo "::group::⬇️ Download JBang"
        curl -Ls https://sh.jbang.dev | bash -s - app setup
        echo "${HOME}/.jbang/bin" >> $GITHUB_PATH
        ${HOME}/.jbang/bin/jbang version
        echo "::endgroup::"
      - name: 'Download JBang (Windows)'
        if: runner.os == 'Windows'
        run: |
          echo "::group::⬇️ Download JBang"
          iex "& { $(iwr https://ps.jbang.dev) } app setup"
          echo "${HOME}/.jbang/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          ${HOME}/.jbang/bin/jbang version
          echo "::endgroup::"
