name: Setup JBang

description: 'Set up a specific version of JBang and add it to the PATH'

branding:
  icon: 'archive'
  color: 'gray-dark'

inputs:
  version:
    description: 'The version of JBang to download'
    default: 'latest'
    required: true

  setup-java:
    default: 'true'
    description: 'Setup internal Java runtime.'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 'Setup Java'
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v 3.11.0
      if: ${{ inputs.setup-java == 'true' }}
      with:
        java-version: 17
        distribution: 'temurin'

    - name: 'Download JBang'
      shell: bash
      #working-directory: ${{ inputs.working-directory }}
      run: |
        echo "::group::⬇️ Download JBang"
        curl -Ls https://sh.jbang.dev | bash -s - app setup
        echo "${HOME}/.jbang/bin" >> $GITHUB_PATH
        jbang version
        echo "::endgroup::"
